interface FalImageResult {
  url: string;
  width: number;
  height: number;
}

export async function generateImageWithFal(
  prompt: string,
  sceneImageUrl: string,
  resolution: string = "1024x1024"
): Promise<FalImageResult> {
  try {
    const [width, height] = resolution.split('x').map(Number);
    
    const response = await fetch("https://fal.run/fal-ai/flux/schnell", {
      method: "POST",
      headers: {
        "Authorization": `Key ${process.env.FAL_API_KEY || "2fd637d9-6952-44a0-a5c2-1ab874fd3fa9:8924390041c47891bb58f6260270ad6e"}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
        image_url: sceneImageUrl,
        width,
        height,
        num_inference_steps: 4, // Schnell model uses 4 steps
        enable_safety_checker: true,
      }),
    });

    if (!response.ok) {
      throw new Error(`Fal.ai API error: ${response.status}`);
    }

    const result = await response.json();
    
    if (!result.images || result.images.length === 0) {
      throw new Error("No images generated by Fal.ai");
    }

    return {
      url: result.images[0].url,
      width: result.images[0].width,
      height: result.images[0].height,
    };
  } catch (error) {
    console.error("Fal.ai API error:", error);
    throw new Error("Failed to generate image with Fal.ai");
  }
}
